// <auto-generated />
// Scaffolded from existing SQL Server database - Database First approach
// DO NOT EDIT MANUALLY - Changes will be overwritten by scaffolding
// Physical table/column names preserved exactly as in legacy schema (INV-01)

using Microsoft.EntityFrameworkCore;
using IKMS.Domain.Entities;

namespace IKMS.Infrastructure.Data;

public class IkmsDbContext : DbContext
{
    public IkmsDbContext(DbContextOptions<IkmsDbContext> options)
        : base(options)
    {
    }

    // DbSet properties for all 36 tables from Appendix schema
    public DbSet<User> Users { get; set; } = null!;
    public DbSet<Organization> Organizations { get; set; } = null!;
    public DbSet<OrganizationUser> OrganizationUsers { get; set; } = null!;
    public DbSet<Role> Roles { get; set; } = null!;
    public DbSet<UserRole> UserRoles { get; set; } = null!;
    public DbSet<ApiEndpoint> ApiEndpoints { get; set; } = null!;
    public DbSet<Permission> Permissions { get; set; } = null!;
    public DbSet<AuthSession> AuthSessions { get; set; } = null!;
    public DbSet<AuthRefreshToken> AuthRefreshTokens { get; set; } = null!;
    public DbSet<AuthAccessTokenBlacklist> AuthAccessTokenBlacklists { get; set; } = null!;
    public DbSet<AuthLoginLockout> AuthLoginLockouts { get; set; } = null!;
    public DbSet<Domain> Domains { get; set; } = null!;
    public DbSet<Module> Modules { get; set; } = null!;
    public DbSet<Term> Terms { get; set; } = null!;
    public DbSet<State> States { get; set; } = null!;
    public DbSet<Tmd> TMDs { get; set; } = null!;
    public DbSet<RelationsType> RelationsTypes { get; set; } = null!;
    public DbSet<Mrt> MRTs { get; set; } = null!;
    public DbSet<RelationConstraint> RelationConstraints { get; set; } = null!;
    public DbSet<Relation> Relations { get; set; } = null!;
    public DbSet<DocContent> DocContents { get; set; } = null!;
    public DbSet<File> Files { get; set; } = null!;
    public DbSet<Log> Logs { get; set; } = null!;
    public DbSet<LogType> LogTypes { get; set; } = null!;
    public DbSet<News> News { get; set; } = null!;
    public DbSet<NewsCategory> NewsCategories { get; set; } = null!;
    public DbSet<NewsRelNewsCategory> NewsRelNewsCategories { get; set; } = null!;
    public DbSet<NewsRelTag> NewsRelTags { get; set; } = null!;
    public DbSet<ProjectType> ProjectTypes { get; set; } = null!;
    public DbSet<Project> Projects { get; set; } = null!;
    public DbSet<Process> Processes { get; set; } = null!;
    public DbSet<ProjectUser> ProjectUsers { get; set; } = null!;
    public DbSet<Payment> Payments { get; set; } = null!;
    public DbSet<Tmdp> TMDPs { get; set; } = null!;
    public DbSet<Theme> Themes { get; set; } = null!;
    public DbSet<ThemeType> ThemeTypes { get; set; } = null!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Apply all entity configurations from the schema
        new UserConfiguration().Configure(modelBuilder.Entity<User>());
        new OrganizationConfiguration().Configure(modelBuilder.Entity<Organization>());
        new OrganizationUserConfiguration().Configure(modelBuilder.Entity<OrganizationUser>());
        new RoleConfiguration().Configure(modelBuilder.Entity<Role>());
        new UserRoleConfiguration().Configure(modelBuilder.Entity<UserRole>());
        new ApiEndpointConfiguration().Configure(modelBuilder.Entity<ApiEndpoint>());
        new PermissionConfiguration().Configure(modelBuilder.Entity<Permission>());
        new AuthSessionConfiguration().Configure(modelBuilder.Entity<AuthSession>());
        new AuthRefreshTokenConfiguration().Configure(modelBuilder.Entity<AuthRefreshToken>());
        new AuthAccessTokenBlacklistConfiguration().Configure(modelBuilder.Entity<AuthAccessTokenBlacklist>());
        new AuthLoginLockoutConfiguration().Configure(modelBuilder.Entity<AuthLoginLockout>());
        new DomainConfiguration().Configure(modelBuilder.Entity<Domain>());
        new ModuleConfiguration().Configure(modelBuilder.Entity<Module>());
        new TermConfiguration().Configure(modelBuilder.Entity<Term>());
        new StateConfiguration().Configure(modelBuilder.Entity<State>());
        new TmdConfiguration().Configure(modelBuilder.Entity<Tmd>());
        new RelationsTypeConfiguration().Configure(modelBuilder.Entity<RelationsType>());
        new MrtConfiguration().Configure(modelBuilder.Entity<Mrt>());
        new RelationConstraintConfiguration().Configure(modelBuilder.Entity<RelationConstraint>());
        new RelationConfiguration().Configure(modelBuilder.Entity<Relation>());
        new DocContentConfiguration().Configure(modelBuilder.Entity<DocContent>());
        new FileConfiguration().Configure(modelBuilder.Entity<File>());
        new LogConfiguration().Configure(modelBuilder.Entity<Log>());
        new LogTypeConfiguration().Configure(modelBuilder.Entity<LogType>());
        new NewsConfiguration().Configure(modelBuilder.Entity<News>());
        new NewsCategoryConfiguration().Configure(modelBuilder.Entity<NewsCategory>());
        new NewsRelNewsCategoryConfiguration().Configure(modelBuilder.Entity<NewsRelNewsCategory>());
        new NewsRelTagConfiguration().Configure(modelBuilder.Entity<NewsRelTag>());
        new ProjectTypeConfiguration().Configure(modelBuilder.Entity<ProjectType>());
        new ProjectConfiguration().Configure(modelBuilder.Entity<Project>());
        new ProcessConfiguration().Configure(modelBuilder.Entity<Process>());
        new ProjectUserConfiguration().Configure(modelBuilder.Entity<ProjectUser>());
        new PaymentConfiguration().Configure(modelBuilder.Entity<Payment>());
        new TmdpConfiguration().Configure(modelBuilder.Entity<Tmdp>());
        new ThemeConfiguration().Configure(modelBuilder.Entity<Theme>());
        new ThemeTypeConfiguration().Configure(modelBuilder.Entity<ThemeType>());

        // Disable migrations guard - INV-02
        // This context is Database-First, Migrations folder must stay empty
    }

    public override int SaveChanges()
    {
        // Future: Add audit logging hook here (CONV-09)
        return base.SaveChanges();
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        // Future: Add audit logging hook here (CONV-09)
        return base.SaveChangesAsync(cancellationToken);
    }
}

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8604 // Possible null reference argument.
